// <auto-generated />
using System;
using BankDataService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20241013073426_IsAdminImpl")]
    partial class IsAdminImpl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("BankDataService.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountHolderName = "Robert Martinez",
                            Balance = 2213m,
                            CreatedAt = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 2,
                            AccountHolderName = "David Garcia",
                            Balance = 10870m,
                            CreatedAt = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 3,
                            AccountHolderName = "Laura Martinez",
                            Balance = 4221m,
                            CreatedAt = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 4,
                            AccountHolderName = "Olivia Davis",
                            Balance = 6723m,
                            CreatedAt = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 5,
                            AccountHolderName = "Laura Williams",
                            Balance = 8577m,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 6,
                            AccountHolderName = "Laura Brown",
                            Balance = 3963m,
                            CreatedAt = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 7,
                            AccountHolderName = "John Williams",
                            Balance = 8772m,
                            CreatedAt = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 8,
                            AccountHolderName = "Michael Miller",
                            Balance = 3724m,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 9,
                            AccountHolderName = "Michael Martinez",
                            Balance = 7712m,
                            CreatedAt = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 10,
                            AccountHolderName = "Robert Brown",
                            Balance = 2394m,
                            CreatedAt = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BankDataService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountId = 1,
                            Amount = 241m,
                            TransactionDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountId = 1,
                            Amount = 857m,
                            TransactionDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountId = 2,
                            Amount = 713m,
                            TransactionDate = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountId = 2,
                            Amount = 732m,
                            TransactionDate = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountId = 2,
                            Amount = 991m,
                            TransactionDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountId = 2,
                            Amount = 649m,
                            TransactionDate = new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountId = 3,
                            Amount = 83m,
                            TransactionDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountId = 3,
                            Amount = 143m,
                            TransactionDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountId = 3,
                            Amount = 704m,
                            TransactionDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountId = 3,
                            Amount = 186m,
                            TransactionDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountId = 4,
                            Amount = 853m,
                            TransactionDate = new DateTime(2024, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountId = 4,
                            Amount = 696m,
                            TransactionDate = new DateTime(2024, 6, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountId = 4,
                            Amount = 742m,
                            TransactionDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountId = 4,
                            Amount = 464m,
                            TransactionDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountId = 5,
                            Amount = 158m,
                            TransactionDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountId = 5,
                            Amount = 958m,
                            TransactionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountId = 5,
                            Amount = 438m,
                            TransactionDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountId = 5,
                            Amount = 57m,
                            TransactionDate = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountId = 6,
                            Amount = 255m,
                            TransactionDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountId = 6,
                            Amount = 274m,
                            TransactionDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountId = 7,
                            Amount = 227m,
                            TransactionDate = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountId = 7,
                            Amount = 248m,
                            TransactionDate = new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountId = 8,
                            Amount = 269m,
                            TransactionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountId = 9,
                            Amount = 856m,
                            TransactionDate = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountId = 10,
                            Amount = 978m,
                            TransactionDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountId = 10,
                            Amount = 170m,
                            TransactionDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        });
                });

            modelBuilder.Entity("BankDataService.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            Address = "518 Main St, Phoenix",
                            Email = "robert.martinez@gmail.com",
                            IsAdmin = true,
                            Name = "Robert Martinez",
                            Password = "passwordRobert",
                            Phone = "944-735-1537",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKwSURBVHhe7dHRkcMwDAPR9N90rgGMaPsEUA73zeDbovfzxUiEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQ7WH/3w+P7W3ILx5pyJ8cCchfMNOQPjGdSJ887oQ/oB1IPwhSyP8QUsi/EFLel34E6l3Pl0K4TdTb767BMIbqHffWQLhjdT7r86N8GbqhitzI3yAuqOaG+FD1C3VnAgfom6p5kT4IHXPak6ED1L3VHMhfJC6p5oL4cPUTau5ED5M3bSaC+HD1E2ruRA+TN20mgvhw9RNq7kQPkzdtJoL4cPUTau5ED5M3bSaC+GD1D3VXAgfpO6p5kL4IHXPak6ED1L3rOZE+BB1SzUnwgeoO6q5ET5A3VHNjfBm6oYrcyO8iXr71SUQfjP15jtLIfwG6p1Pl0L4m9Sbdi3pdeF/dWmEP2AdCN+8LoRvWjfCN+wEhA/uJIQP7ESEN+10hN+8tyC8aad7XXgX9a0dOxXhC+oNT3Yawt+g3nNnJyH8TepNd3YKwj+k3nZ1JyD8P6j3XdkJCP9P6o1X1o3wG6h3Xlknwm+i3lqtE+E3Uu+t1oXwm6k3r9aF8JupN1frQHgD9e7VOhDeQL27WhrhTdTbV0sjvIl6e7Ukwpuot1dLIryRev9qSYQ3Uu+vlkJ4I/X+aimEN1M3rJZCeDN1Q7UEwpupG6olED5A3VHNjfAB6o5qboQPUHdUcyN8iLqlmhPhQ9Qt1ZwIH6TuWc2J8EHqnmouhA9S91RzIXyYumk1F8KHqZuqORA+TN1UzYHwDdRd1XYjfAN1V7XdCN9A3VVtN8I3UbdV24nwTdRt1Xb6nT+JWwg/FOGHIvxQhB+K8EMRfijCD0X4kb7fP15QBKB5xkTEAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            UserProfileId = 2,
                            Address = "958 Cherry St, Los Angeles",
                            Email = "david.garcia@gmail.com",
                            IsAdmin = false,
                            Name = "David Garcia",
                            Password = "passwordDavid",
                            Phone = "729-604-8121",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAK1SURBVHhe7dHRDcMwDAPR7r90uwBhOY0oOdE9gL+Jhft8MRLhhyL8UIQfivBDEX4owg9F+KEIPxThhyL8UIQfivBDEX4owg9F+KEIPxThhyL8UIQfivBDEX4owg9F+KEIPxThhyL8UO3hP5/P0Xsrwv+xNyB8wp6I8Il7EsIb9gSEN+9UhC/YiQhfuJMQvninIHzDTvC48A7qPxXrRPgN6h1Z60L4i9Sb7q4D4W9Q7/tnHQifQL3z6qoRPpF675VVInwy9eYrq0J4A/Xu3VUhvIl6++4qEN5IvX9nFQhvpm7YmRvhC6g7orkRvoC6Y2dOhC+ibonmRPgi6paduRC+kLonmgvhC6l7orkQvpi6aTUXwhdTN0VzIHwxdVM0B8I3UHet5kD4Buqu1RwI30DdFS0b4Ruou6JlI3wDdVe0bIRvom5bLRvhm6jbVstG+CbqttWyEb6Jum21bIRvom5bLRvhm6jbVstG+CbqtmiZCN9E3RYtE+GbqNuiZSJ8E3VbtEyEb6Jui5aJ8E3UbdEyEb6Jui1aJsI3Ubetlo3wTdRtq2UjfBN122rZCN9E3bZaNsI3Ubetlo3wTdRtq2UjfBN122rZCN9A3RUtG+EbqLuiZSN8A3XXag6Eb6DuWs2B8MXUTdEcCF9M3RTNgfDF1E3RHAhfSN0TzYXwhdQ90VwIX0jdE82F8EXULdGcCF9E3RLNifAF1B3R3Ahvpm7YmRvhzdQNO3MjvJF6/84qEN5EvX13FQhvoN69uyqET6bevLtKhE+k3ntllQifQL3z6qoR/gb1vn/WgfAXqTfdWRfCB9QbstZpdHj1/ap1e1z4N+wEhC/eKQhftNMQvmAnIrxxJyO8YU9A+MQ9CeFv7qkIf3FvQfhgb/Xey7BE+KEIPxThhyL8UIQfivBDEX4owo/0/f4ARZg+dAE/yWkAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 3,
                            Address = "822 Walnut St, Chicago",
                            Email = "laura.martinez@gmail.com",
                            IsAdmin = false,
                            Name = "Laura Martinez",
                            Password = "passwordLaura",
                            Phone = "738-946-6749",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFTSURBVHhe7dHBCcNAEATByz/pUwwGL1rRVTD/gT6XJOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI96Pfw556fxH8JHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfNTnwn9tWwk/vK2EH95Wwg9vK+GHt5Xww9tK+OFtJfzwthJ+eFsJP7yt9j5jlPBRwkcJHyV8lPBRwkcJHyV80r0PU2FnLFKaa9EAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 4,
                            Address = "273 Pine St, Houston",
                            Email = "olivia.davis@gmail.com",
                            IsAdmin = false,
                            Name = "Olivia Davis",
                            Password = "passwordOlivia",
                            Phone = "289-709-2983",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAOnSURBVHhe7ZPRCmMhDAX7/z/dXR8KyzIY49XricnAPBVac4Z+vkVKKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKvxfPp+PyxtIFZ4irjQS14enQG+ozpXhKcRJFbkqPI2upBJXhKeRlVUgfHgaNoKnCRuexozoKUKGpwEje4JQ4Wm0W3ybMOFprJ3+oM92+hYhwtNAK3wKfecK30A+PA3zxJ3Q7826G+nwNMiMb0NvmHEnsuFpiBlPQW+ZcRfXhleB3uZxF5LhaQCPatAbPe5AbiU63KMy9N5RVyO1FB08ahTo7aOu5Irw0aAbRlyJzGp06IhRoVtGXEWFPwTdMuIqJJajA0eMDt004gqOr0eHjXgLdJvlCkKGvwm6b8SnVHgB6EbLpxxdkQ6yvBW61fIJFV4EutXyCceWpENGvBW61fIJocLfDt1sOUuFF4JutpzlyJp0gGUW6Paes1R4Meh2yxkqvBh0u+UMFV4Mut1yhhDhs0Eb9Jzh9VXp4ZbZoA16zlDhBaENLL1UeEFoA0svFV4Q2sDSi3z4jNAOll4qvCC0g6WXCi8KbdHTS4UXhbbo6aXCi0Jb9PRS4UWhLXp6qfCi0BY9vVR4UWiLnl4qvCi0RU8vFV4U2qKnlwovCm3R00uFF4W26OmlwgtCO1h6qfCC0A6WXuTDN7NBG1h6qfCC0AaWXiq8ILSBpZcKLwht0HOGI6vS43tmgzboOUOI8M0s0O2WM1R4Meh2yxkqvBh0u+UMxxalA3pmgW7vOUuY8M3boZstZ6nwQtDNlrOECt+8FbrV8glHl6RjLG+FbrV8QoUXgO4c8QnHl6SDLG+DbrR8SsjwzVug20Z8isSCdJjlLdBtlisIG74ZHbppxBXIrEcHjhgVumXEVVT4Q9AtI65Cajk6dMRo0A0jruSK8M0I0LtHXY3cYnS0R1XorR5XI7kUHe5RDXqjxx3I/kVoAI8q0Ns87kI2fIOG8HoKeovXnVwfvvk29IYZdyIdvkGDPHEX9FtP3I18+AYNs8Kn0Heu8A1ChG/QQDv9QZ/t9C3ChP9BY93g24QL36DhInuCkOEbNGBETxE2/A8aM4KnCR++QcMqq8AV4X/QyEoqcVX4HzT6SRW5Mvy/UIg3VOf68P9DkVYZiXThCYrY8wYqfFIqfFIqfFIqfFIqfFIqfFIqfEq+3z8+b1xWzv2W6AAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            UserProfileId = 5,
                            Address = "850 Cedar Ave, Philadelphia",
                            Email = "laura.williams@gmail.com",
                            IsAdmin = false,
                            Name = "Laura Williams",
                            Password = "passwordLaura",
                            Phone = "625-304-9983",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFTSURBVHhe7dHBCcNAEATByz/pUwwGL1rRVTD/gT6XJOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI96Pfw556fxH8JHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfNTnwn9tWwk/vK2EH95Wwg9vK+GHt5Xww9tK+OFtJfzwthJ+eFsJP7yt9j5jlPBRwkcJHyV8lPBRwkcJHyV80r0PU2FnLFKaa9EAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 6,
                            Address = "498 Main St, San Antonio",
                            Email = "laura.brown@gmail.com",
                            IsAdmin = false,
                            Name = "Laura Brown",
                            Password = "passwordLaura",
                            Phone = "253-145-4593",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFTSURBVHhe7dHBCcNAEATByz/pUwwGL1rRVTD/gT6XJOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI96Pfw556fxH8JHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfNTnwn9tWwk/vK2EH95Wwg9vK+GHt5Xww9tK+OFtJfzwthJ+eFsJP7yt9j5jlPBRwkcJHyV8lPBRwkcJHyV80r0PU2FnLFKaa9EAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 7,
                            Address = "115 Maple St, Philadelphia",
                            Email = "john.williams@gmail.com",
                            IsAdmin = false,
                            Name = "John Williams",
                            Password = "passwordJohn",
                            Phone = "278-549-9807",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIvSURBVHhe7dFBbsJQEARR7n9pIlaJopHtTsD+rq4n9RKs+fV4qpLhSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+VHX4x+MRjcTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFITrlmesStnWX69tZIDB+MxPDBSAwfjKQ2/PTdrdEY/uBolgz/2qdN39wajeEPjsbwB0dz2kXTY27tk6bv7Y1m2fCvfcr0ra0RGf7AiJYO/9q7Td/YG9GpV02PemTvMv333qhuEf61/5r+88ioTr9setyj+4vpf5JR3Sr8z+2ZfpOO7JLrpkdecWSXXTc99EqjM/ywBpdeOT36Cmtw+ZXTw1+5FktcOgU4e22WungKcsYaLXf1FOaTa7Xs5VOkd67dLV5gCveX6dstX2OK+nva5guVMnwpw5cyfCnDlzJ8KcNXej6/ADqIE4A0DE9uAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            UserProfileId = 8,
                            Address = "722 Highland Ave, Houston",
                            Email = "michael.miller@gmail.com",
                            IsAdmin = false,
                            Name = "Michael Miller",
                            Password = "passwordMichael",
                            Phone = "282-947-9422",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAR5SURBVHhe7ZHRiq0wEAT3/3/63g2cBZFqbWOiR6cL6slkJlI//0JJEr4oCV+UhC9Kwhcl4YuS8EVJ+KIkfFESvigJX5SEL0rCFyXhi5LwRUn4oiR8URK+KAlflIQvSsIXJeGLkvBFSfiiJHxREr4oCV+U28P//PwM8Q3Qf/XokPBfAv1Trw6vCd98MvQ/vTok/JdA/9OrQ8J/AfQvZ3R4VfjmE6H/OKNDwn8B9B9ndEj4m6F/OKvD68I3nwS9/6wOCX8z9P6zOiT8jdDbR+jwyvDNJ0DvHqFDwt8IvXuEDgl/E/TmUTo8KnzP+W+F3qvsOb9Hwt8EvVfZc36PhL8BeuuWR+84PC58g74pvxF6p/IP+qZ0SPgboHcq/6BvSoeEvwF6p/IP+qZ0eGT4Bn1XfhP0PuUS+q50SPiLofcpl9B3pUPCXwy9T7mEvisdHhu+QWeU3wC9S7mGzigdEv5C6F3KNXRG6ZDwF0LvIgk6p3R4dPgGnSPvht6kJOic0qFM+Oad0HuUBJ1TOiT8RdB7SAWdVTo8PnyDzpJ3QW9RKuis0qFU+OYd0DuUCjqrdEj4C6B3kFvQeaXDK8I36Dx5NfQG5RZ0XulQLnzzSmi/cgs6r3RI+MnQfnIPuqN0eE34Bt0hr4J2K/egO0qHkuGbV0B7lXvQHaVDwk+E9pIOdE/p8KrwDbpHzoZ2Kh3ontKhbPjmTGif0oHuKR0SfhK0j3Shu0qH14Vv0F1yFrRL6UJ3lQ6lwzdnQHuULnRX6ZDwE6A95BHovtLhleEbdJ8cDe1QHoHuKx3Kh2+OhOYrj0D3lQ4J/+tIaD55FJqhdHht+AbNIEdBs5VHoRlKh4T/OAKaqzwKzVA6JPzHEdBcsgeao3R4dfgGzSHPQjOVPdAcpUPCLzwDzVP2QHOUDgm/8Aw0j+yFZikdXh++QbPIXmiWsheapXRI+JU90BxlLzRL6ZDwK3ugOeQZaJ7SoUT4Bs0jj0IzlGegeUqHhAePQPeVZ6B5SoeEB49A98mz0EylQ5nwDZpJutBd5VloptIh4YUOdE95FpqpdEh4oQPdI0dAc5UOpcI3aC65B91RjoDmKh0SfsMt6LxyBDRX6ZDwG25B58lR0GylQ7nwDZpNKuischQ0W+mQ8Bsq6KxyFDRb6ZDwOxJ0jhwJzVc6lAzfoPnkGjqjHAnNVzok/I5r6IxyJDRf6ZDwhkvoOzka2qF0KBu+QTvIJfSdHA3tUDokvOEf9E05GtqhdEh40yPnZ0B7lA6lwzdoD3n07Ghoj9Ih4WHPWWdAe5QOCQ97zjgL2qV0KB++Qbt6nQXtUjok/C+0q9dZ0C6lQ8L/Qrt6nAntUzok/Afad9SZ0D6lQ8J/oH1HnQntUzok/Afad8TZ0E6lQ8IvoJ2us6GdSoeEX0A7XWdDO5UOCb+AdjpeAe1VOiT8Ctq75xXQXqVDwq+gvXteAe1VOiT8Ctq75VXQbqVDwgO0W3kVtFvpcHv4cA8JX5SEL0rCFyXhi5LwRUn4oiR8URK+JP/+/QdKhfUicXLLiQAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            UserProfileId = 9,
                            Address = "258 Maple St, Los Angeles",
                            Email = "michael.martinez@gmail.com",
                            IsAdmin = false,
                            Name = "Michael Martinez",
                            Password = "passwordMichael",
                            Phone = "238-729-6015",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAR5SURBVHhe7ZHRiq0wEAT3/3/63g2cBZFqbWOiR6cL6slkJlI//0JJEr4oCV+UhC9Kwhcl4YuS8EVJ+KIkfFESvigJX5SEL0rCFyXhi5LwRUn4oiR8URK+KAlflIQvSsIXJeGLkvBFSfiiJHxREr4oCV+U28P//PwM8Q3Qf/XokPBfAv1Trw6vCd98MvQ/vTok/JdA/9OrQ8J/AfQvZ3R4VfjmE6H/OKNDwn8B9B9ndEj4m6F/OKvD68I3nwS9/6wOCX8z9P6zOiT8jdDbR+jwyvDNJ0DvHqFDwt8IvXuEDgl/E/TmUTo8KnzP+W+F3qvsOb9Hwt8EvVfZc36PhL8BeuuWR+84PC58g74pvxF6p/IP+qZ0SPgboHcq/6BvSoeEvwF6p/IP+qZ0eGT4Bn1XfhP0PuUS+q50SPiLofcpl9B3pUPCXwy9T7mEvisdHhu+QWeU3wC9S7mGzigdEv5C6F3KNXRG6ZDwF0LvIgk6p3R4dPgGnSPvht6kJOic0qFM+Oad0HuUBJ1TOiT8RdB7SAWdVTo8PnyDzpJ3QW9RKuis0qFU+OYd0DuUCjqrdEj4C6B3kFvQeaXDK8I36Dx5NfQG5RZ0XulQLnzzSmi/cgs6r3RI+MnQfnIPuqN0eE34Bt0hr4J2K/egO0qHkuGbV0B7lXvQHaVDwk+E9pIOdE/p8KrwDbpHzoZ2Kh3ontKhbPjmTGif0oHuKR0SfhK0j3Shu0qH14Vv0F1yFrRL6UJ3lQ6lwzdnQHuULnRX6ZDwE6A95BHovtLhleEbdJ8cDe1QHoHuKx3Kh2+OhOYrj0D3lQ4J/+tIaD55FJqhdHht+AbNIEdBs5VHoRlKh4T/OAKaqzwKzVA6JPzHEdBcsgeao3R4dfgGzSHPQjOVPdAcpUPCLzwDzVP2QHOUDgm/8Aw0j+yFZikdXh++QbPIXmiWsheapXRI+JU90BxlLzRL6ZDwK3ugOeQZaJ7SoUT4Bs0jj0IzlGegeUqHhAePQPeVZ6B5SoeEB49A98mz0EylQ5nwDZpJutBd5VloptIh4YUOdE95FpqpdEh4oQPdI0dAc5UOpcI3aC65B91RjoDmKh0SfsMt6LxyBDRX6ZDwG25B58lR0GylQ7nwDZpNKuischQ0W+mQ8Bsq6KxyFDRb6ZDwOxJ0jhwJzVc6lAzfoPnkGjqjHAnNVzok/I5r6IxyJDRf6ZDwhkvoOzka2qF0KBu+QTvIJfSdHA3tUDokvOEf9E05GtqhdEh40yPnZ0B7lA6lwzdoD3n07Ghoj9Ih4WHPWWdAe5QOCQ97zjgL2qV0KB++Qbt6nQXtUjok/C+0q9dZ0C6lQ8L/Qrt6nAntUzok/Afad9SZ0D6lQ8J/oH1HnQntUzok/Afad8TZ0E6lQ8IvoJ2us6GdSoeEX0A7XWdDO5UOCb+AdjpeAe1VOiT8Ctq75xXQXqVDwq+gvXteAe1VOiT8Ctq75VXQbqVDwgO0W3kVtFvpcHv4cA8JX5SEL0rCFyXhi5LwRUn4oiR8URK+JP/+/QdKhfUicXLLiQAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            UserProfileId = 10,
                            Address = "990 Cedar Ave, New York",
                            Email = "robert.brown@gmail.com",
                            IsAdmin = false,
                            Name = "Robert Brown",
                            Password = "passwordRobert",
                            Phone = "282-976-2895",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKwSURBVHhe7dHRkcMwDAPR9N90rgGMaPsEUA73zeDbovfzxUiEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQ7WH/3w+P7W3ILx5pyJ8cCchfMNOQPjGdSJ887oQ/oB1IPwhSyP8QUsi/EFLel34E6l3Pl0K4TdTb767BMIbqHffWQLhjdT7r86N8GbqhitzI3yAuqOaG+FD1C3VnAgfom6p5kT4IHXPak6ED1L3VHMhfJC6p5oL4cPUTau5ED5M3bSaC+HD1E2ruRA+TN20mgvhw9RNq7kQPkzdtJoL4cPUTau5ED5M3bSaC+GD1D3VXAgfpO6p5kL4IHXPak6ED1L3rOZE+BB1SzUnwgeoO6q5ET5A3VHNjfBm6oYrcyO8iXr71SUQfjP15jtLIfwG6p1Pl0L4m9Sbdi3pdeF/dWmEP2AdCN+8LoRvWjfCN+wEhA/uJIQP7ESEN+10hN+8tyC8aad7XXgX9a0dOxXhC+oNT3Yawt+g3nNnJyH8TepNd3YKwj+k3nZ1JyD8P6j3XdkJCP9P6o1X1o3wG6h3Xlknwm+i3lqtE+E3Uu+t1oXwm6k3r9aF8JupN1frQHgD9e7VOhDeQL27WhrhTdTbV0sjvIl6e7Ukwpuot1dLIryRev9qSYQ3Uu+vlkJ4I/X+aimEN1M3rJZCeDN1Q7UEwpupG6olED5A3VHNjfAB6o5qboQPUHdUcyN8iLqlmhPhQ9Qt1ZwIH6TuWc2J8EHqnmouhA9S91RzIXyYumk1F8KHqZuqORA+TN1UzYHwDdRd1XYjfAN1V7XdCN9A3VVtN8I3UbdV24nwTdRt1Xb6nT+JWwg/FOGHIvxQhB+K8EMRfijCD0X4kb7fP15QBKB5xkTEAAAAAElFTkSuQmCC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
