// <auto-generated />
using System;
using BankDataService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20241012030439_TestData2")]
    partial class TestData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("BankDataService.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountHolderName = "Laura Johnson",
                            Balance = 6800m,
                            CreatedAt = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 2,
                            AccountHolderName = "Laura Miller",
                            Balance = 5473m,
                            CreatedAt = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 3,
                            AccountHolderName = "James Smith",
                            Balance = 3909m,
                            CreatedAt = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 4,
                            AccountHolderName = "James Martinez",
                            Balance = 7354m,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 5,
                            AccountHolderName = "Olivia Johnson",
                            Balance = 9272m,
                            CreatedAt = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 6,
                            AccountHolderName = "David Smith",
                            Balance = 3644m,
                            CreatedAt = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 7,
                            AccountHolderName = "John Brown",
                            Balance = 8665m,
                            CreatedAt = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 8,
                            AccountHolderName = "Sarah Smith",
                            Balance = 3624m,
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 9,
                            AccountHolderName = "James Garcia",
                            Balance = 6524m,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AccountId = 10,
                            AccountHolderName = "Robert Williams",
                            Balance = 7395m,
                            CreatedAt = new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BankDataService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountId = 1,
                            Amount = 435m,
                            TransactionDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountId = 1,
                            Amount = 346m,
                            TransactionDate = new DateTime(2024, 7, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountId = 1,
                            Amount = 640m,
                            TransactionDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountId = 1,
                            Amount = 190m,
                            TransactionDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountId = 2,
                            Amount = 692m,
                            TransactionDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountId = 3,
                            Amount = 524m,
                            TransactionDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountId = 3,
                            Amount = 93m,
                            TransactionDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountId = 3,
                            Amount = 533m,
                            TransactionDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountId = 4,
                            Amount = 178m,
                            TransactionDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountId = 4,
                            Amount = 668m,
                            TransactionDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountId = 5,
                            Amount = 469m,
                            TransactionDate = new DateTime(2024, 7, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountId = 5,
                            Amount = 639m,
                            TransactionDate = new DateTime(2023, 11, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountId = 5,
                            Amount = 105m,
                            TransactionDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountId = 5,
                            Amount = 115m,
                            TransactionDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountId = 6,
                            Amount = 883m,
                            TransactionDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountId = 7,
                            Amount = 461m,
                            TransactionDate = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountId = 7,
                            Amount = 996m,
                            TransactionDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountId = 8,
                            Amount = 560m,
                            TransactionDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountId = 9,
                            Amount = 434m,
                            TransactionDate = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountId = 9,
                            Amount = 763m,
                            TransactionDate = new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountId = 9,
                            Amount = 783m,
                            TransactionDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountId = 9,
                            Amount = 601m,
                            TransactionDate = new DateTime(2024, 8, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountId = 10,
                            Amount = 899m,
                            TransactionDate = new DateTime(2024, 8, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountId = 10,
                            Amount = 297m,
                            TransactionDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionType = "Withdrawal"
                        });
                });

            modelBuilder.Entity("BankDataService.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            Address = "625 Walnut St, Dallas",
                            Email = "laura.johnson@gmail.com",
                            Name = "Laura Johnson",
                            Password = "passwordLaura",
                            Phone = "593-708-7187",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFTSURBVHhe7dHBCcNAEATByz/pUwwGL1rRVTD/gT6XJOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI96Pfw556fxH8JHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfNTnwn9tWwk/vK2EH95Wwg9vK+GHt5Xww9tK+OFtJfzwthJ+eFsJP7yt9j5jlPBRwkcJHyV8lPBRwkcJHyV80r0PU2FnLFKaa9EAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 2,
                            Address = "942 Walnut St, Dallas",
                            Email = "laura.miller@gmail.com",
                            Name = "Laura Miller",
                            Password = "passwordLaura",
                            Phone = "834-533-3899",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFTSURBVHhe7dHBCcNAEATByz/pUwwGL1rRVTD/gT6XJOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI8SPkr4KOGjhI96Pfw556fxH8JHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfJTwUcJHCR8lfNTnwn9tWwk/vK2EH95Wwg9vK+GHt5Xww9tK+OFtJfzwthJ+eFsJP7yt9j5jlPBRwkcJHyV8lPBRwkcJHyV80r0PU2FnLFKaa9EAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 3,
                            Address = "347 Cherry St, New York",
                            Email = "james.smith@gmail.com",
                            Name = "James Smith",
                            Password = "passwordJames",
                            Phone = "557-947-8180",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIvSURBVHhe7dFBbsJQEARR7n9pIlaJopHtTsD+rq4n9RKs+fV4qpLhSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+VHX4x+MRjcTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFITrlmesStnWX69tZIDB+MxPDBSAwfjKQ2/PTdrdEY/uBolgz/2qdN39wajeEPjsbwB0dz2kXTY27tk6bv7Y1m2fCvfcr0ra0RGf7AiJYO/9q7Td/YG9GpV02PemTvMv333qhuEf61/5r+88ioTr9setyj+4vpf5JR3Sr8z+2ZfpOO7JLrpkdecWSXXTc99EqjM/ywBpdeOT36Cmtw+ZXTw1+5FktcOgU4e22WungKcsYaLXf1FOaTa7Xs5VOkd67dLV5gCveX6dstX2OK+nva5guVMnwpw5cyfCnDlzJ8KcNXej6/ADqIE4A0DE9uAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            UserProfileId = 4,
                            Address = "383 Birch St, Los Angeles",
                            Email = "james.martinez@gmail.com",
                            Name = "James Martinez",
                            Password = "passwordJames",
                            Phone = "189-196-7385",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIvSURBVHhe7dFBbsJQEARR7n9pIlaJopHtTsD+rq4n9RKs+fV4qpLhSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+VHX4x+MRjcTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFITrlmesStnWX69tZIDB+MxPDBSAwfjKQ2/PTdrdEY/uBolgz/2qdN39wajeEPjsbwB0dz2kXTY27tk6bv7Y1m2fCvfcr0ra0RGf7AiJYO/9q7Td/YG9GpV02PemTvMv333qhuEf61/5r+88ioTr9setyj+4vpf5JR3Sr8z+2ZfpOO7JLrpkdecWSXXTc99EqjM/ywBpdeOT36Cmtw+ZXTw1+5FktcOgU4e22WungKcsYaLXf1FOaTa7Xs5VOkd67dLV5gCveX6dstX2OK+nva5guVMnwpw5cyfCnDlzJ8KcNXej6/ADqIE4A0DE9uAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            UserProfileId = 5,
                            Address = "122 Cedar Ave, New York",
                            Email = "olivia.johnson@gmail.com",
                            Name = "Olivia Johnson",
                            Password = "passwordOlivia",
                            Phone = "960-646-4831",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAOnSURBVHhe7ZPRCmMhDAX7/z/dXR8KyzIY49XricnAPBVac4Z+vkVKKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKnxSKvxfPp+PyxtIFZ4irjQS14enQG+ozpXhKcRJFbkqPI2upBJXhKeRlVUgfHgaNoKnCRuexozoKUKGpwEje4JQ4Wm0W3ybMOFprJ3+oM92+hYhwtNAK3wKfecK30A+PA3zxJ3Q7826G+nwNMiMb0NvmHEnsuFpiBlPQW+ZcRfXhleB3uZxF5LhaQCPatAbPe5AbiU63KMy9N5RVyO1FB08ahTo7aOu5Irw0aAbRlyJzGp06IhRoVtGXEWFPwTdMuIqJJajA0eMDt004gqOr0eHjXgLdJvlCkKGvwm6b8SnVHgB6EbLpxxdkQ6yvBW61fIJFV4EutXyCceWpENGvBW61fIJocLfDt1sOUuFF4JutpzlyJp0gGUW6Paes1R4Meh2yxkqvBh0u+UMFV4Mut1yhhDhs0Eb9Jzh9VXp4ZbZoA16zlDhBaENLL1UeEFoA0svFV4Q2sDSi3z4jNAOll4qvCC0g6WXCi8KbdHTS4UXhbbo6aXCi0Jb9PRS4UWhLXp6qfCi0BY9vVR4UWiLnl4qvCi0RU8vFV4U2qKnlwovCm3R00uFF4W26OmlwgtCO1h6qfCC0A6WXuTDN7NBG1h6qfCC0AaWXiq8ILSBpZcKLwht0HOGI6vS43tmgzboOUOI8M0s0O2WM1R4Meh2yxkqvBh0u+UMxxalA3pmgW7vOUuY8M3boZstZ6nwQtDNlrOECt+8FbrV8glHl6RjLG+FbrV8QoUXgO4c8QnHl6SDLG+DbrR8SsjwzVug20Z8isSCdJjlLdBtlisIG74ZHbppxBXIrEcHjhgVumXEVVT4Q9AtI65Cajk6dMRo0A0jruSK8M0I0LtHXY3cYnS0R1XorR5XI7kUHe5RDXqjxx3I/kVoAI8q0Ns87kI2fIOG8HoKeovXnVwfvvk29IYZdyIdvkGDPHEX9FtP3I18+AYNs8Kn0Heu8A1ChG/QQDv9QZ/t9C3ChP9BY93g24QL36DhInuCkOEbNGBETxE2/A8aM4KnCR++QcMqq8AV4X/QyEoqcVX4HzT6SRW5Mvy/UIg3VOf68P9DkVYZiXThCYrY8wYqfFIqfFIqfFIqfFIqfFIqfFIqfEq+3z8+b1xWzv2W6AAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            UserProfileId = 6,
                            Address = "982 Walnut St, Houston",
                            Email = "david.smith@gmail.com",
                            Name = "David Smith",
                            Password = "passwordDavid",
                            Phone = "850-645-1676",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAK1SURBVHhe7dHRDcMwDAPR7r90uwBhOY0oOdE9gL+Jhft8MRLhhyL8UIQfivBDEX4owg9F+KEIPxThhyL8UIQfivBDEX4owg9F+KEIPxThhyL8UIQfivBDEX4owg9F+KEIPxThhyL8UO3hP5/P0Xsrwv+xNyB8wp6I8Il7EsIb9gSEN+9UhC/YiQhfuJMQvninIHzDTvC48A7qPxXrRPgN6h1Z60L4i9Sb7q4D4W9Q7/tnHQifQL3z6qoRPpF675VVInwy9eYrq0J4A/Xu3VUhvIl6++4qEN5IvX9nFQhvpm7YmRvhC6g7orkRvoC6Y2dOhC+ibonmRPgi6paduRC+kLonmgvhC6l7orkQvpi6aTUXwhdTN0VzIHwxdVM0B8I3UHet5kD4Buqu1RwI30DdFS0b4Ruou6JlI3wDdVe0bIRvom5bLRvhm6jbVstG+CbqttWyEb6Jum21bIRvom5bLRvhm6jbVstG+CbqtmiZCN9E3RYtE+GbqNuiZSJ8E3VbtEyEb6Jui5aJ8E3UbdEyEb6Jui1aJsI3Ubetlo3wTdRtq2UjfBN122rZCN9E3bZaNsI3Ubetlo3wTdRtq2UjfBN122rZCN9A3RUtG+EbqLuiZSN8A3XXag6Eb6DuWs2B8MXUTdEcCF9M3RTNgfDF1E3RHAhfSN0TzYXwhdQ90VwIX0jdE82F8EXULdGcCF9E3RLNifAF1B3R3Ahvpm7YmRvhzdQNO3MjvJF6/84qEN5EvX13FQhvoN69uyqET6bevLtKhE+k3ntllQifQL3z6qoR/gb1vn/WgfAXqTfdWRfCB9QbstZpdHj1/ap1e1z4N+wEhC/eKQhftNMQvmAnIrxxJyO8YU9A+MQ9CeFv7qkIf3FvQfhgb/Xey7BE+KEIPxThhyL8UIQfivBDEX4owo/0/f4ARZg+dAE/yWkAAAAASUVORK5CYII="
                        },
                        new
                        {
                            UserProfileId = 7,
                            Address = "345 Cherry St, Dallas",
                            Email = "john.brown@gmail.com",
                            Name = "John Brown",
                            Password = "passwordJohn",
                            Phone = "196-966-3092",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIvSURBVHhe7dFBbsJQEARR7n9pIlaJopHtTsD+rq4n9RKs+fV4qpLhSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+VHX4x+MRjcTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFITrlmesStnWX69tZIDB+MxPDBSAwfjKQ2/PTdrdEY/uBolgz/2qdN39wajeEPjsbwB0dz2kXTY27tk6bv7Y1m2fCvfcr0ra0RGf7AiJYO/9q7Td/YG9GpV02PemTvMv333qhuEf61/5r+88ioTr9setyj+4vpf5JR3Sr8z+2ZfpOO7JLrpkdecWSXXTc99EqjM/ywBpdeOT36Cmtw+ZXTw1+5FktcOgU4e22WungKcsYaLXf1FOaTa7Xs5VOkd67dLV5gCveX6dstX2OK+nva5guVMnwpw5cyfCnDlzJ8KcNXej6/ADqIE4A0DE9uAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            UserProfileId = 8,
                            Address = "501 Highland Ave, Philadelphia",
                            Email = "sarah.smith@gmail.com",
                            Name = "Sarah Smith",
                            Password = "passwordSarah",
                            Phone = "495-467-1849",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAANoSURBVHhe7ZTRbuMwEAPz/z+dg3AXIBfQsmxLu6SWA8xrveK0fb1NSRy+KA5fFIcvisMXxeGL4vBFcfiiOHxRHL4oDl8Uhy+KwxfF4Yvi8EVx+KI4fFEcvigOXxSHL4rDF8Xhi+LwRXH4ojh8UbYP/3q9brk7W70QBZzpTsi/BgWKUB3JF6AQmSoidTUanUklZK5FQ7OqAP2VaFgF2aG+EA2qJiu0l6ERVWWE8io0nrps0F2ERttFJqiuQWM99S7oZ82QBZpL0Eh3XAX61h1Z2CZ8JOj7V2SA4go0zqhZoFuumI10eAbQXSNmk34BGuVMNtCNI2bi8JNAd56ZSerX0RhnMoPuPTMLqfDsoJvPzMLhJ4Pu7pmFw08G3X1mBjLhlUD398zA4ReA7u+ZgcMvAN3fM4O0RdEAPZVA9/fMIHVRNMKRaqA3HJmBwxdFJnzTzMPhiyIVvmnmIBe+aZ6TviIKO6J5hmz4prmPdPiP5joUq6GYdzVj0CyFIj7VHLN1+G/N/1AtgoKtsjp0C6BIUVaC8rUoSoY7Q/s6FCLbnaB/DQrAoDoSL0DDM6mI1NVodCaVkPx1RaMzqYDm/6l/oNGZZEY6/DdoeBYZ2Sb8LyhApmxsG/4XFCNDFsqE/wVFiZKBsuF/QYFWmo3DH4BizTYThx8ARZtlFg5/ERTviVk4/ANQyDtm4PATQDGvmIHDTwRFHTUah58MijpiNA6/ABR2xEgcfhEo7JmROPwiUNgzI3H4haC4PSMJ/Rp6bE910Jt6RuLwi0HvOjKS8HXRg4/cAfSuIyNx+MWgd/WMgjp8Ux30piMjcfjFoDcdGYnDLwa96chI6MM3lUHvOTKSlFXRo3uqgt7SMxKJ8E1F0Dt6RiITvqkGekPPSNLWRA8/Uwl0f89opMI3FUB3nxlN6pJogBGZQfeOGI1k+CYj6M4RM0hfEA1xRRbQbaNmIB/+YybonlGzoPiTQYPcNRL0/StmQhG+gYZ56grQd+6aCU34BhpnpndAP2eG2VCFb6CRdpMBuvANNNYuskAZvoFGU5cJ2vANNJ6qbFCHb6ARlWSFPvwHNCq7zMiE/4AGZlMBufAf0ODZKiEb/hsUIVJFtgj/C4oz0x3YMnwPFPLInSkX3vzF4Yvi8EVx+KI4fFEcvigOX5L3+w+v/DGd3p4PCQAAAABJRU5ErkJggg=="
                        },
                        new
                        {
                            UserProfileId = 9,
                            Address = "449 Oak St, Dallas",
                            Email = "james.garcia@gmail.com",
                            Name = "James Garcia",
                            Password = "passwordJames",
                            Phone = "729-988-3395",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIvSURBVHhe7dFBbsJQEARR7n9pIlaJopHtTsD+rq4n9RKs+fV4qpLhSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+lOFLGb6U4UsZvpThSxm+VHX4x+MRjcTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFIDB+MxPDBSAwfjMTwwUgMH4zE8MFITrlmesStnWX69tZIDB+MxPDBSAwfjKQ2/PTdrdEY/uBolgz/2qdN39wajeEPjsbwB0dz2kXTY27tk6bv7Y1m2fCvfcr0ra0RGf7AiJYO/9q7Td/YG9GpV02PemTvMv333qhuEf61/5r+88ioTr9setyj+4vpf5JR3Sr8z+2ZfpOO7JLrpkdecWSXXTc99EqjM/ywBpdeOT36Cmtw+ZXTw1+5FktcOgU4e22WungKcsYaLXf1FOaTa7Xs5VOkd67dLV5gCveX6dstX2OK+nva5guVMnwpw5cyfCnDlzJ8KcNXej6/ADqIE4A0DE9uAAAAAElFTkSuQmCC"
                        },
                        new
                        {
                            UserProfileId = 10,
                            Address = "334 Elm St, Phoenix",
                            Email = "robert.williams@gmail.com",
                            Name = "Robert Williams",
                            Password = "passwordRobert",
                            Phone = "689-560-4587",
                            Picture = "iVBORw0KGgoAAAANSUhEUgAAAH4AAAB+CAYAAADiI6WIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAKwSURBVHhe7dHRkcMwDAPR9N90rgGMaPsEUA73zeDbovfzxUiEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQxF+KMIPRfihCD8U4Yci/FCEH4rwQ7WH/3w+P7W3ILx5pyJ8cCchfMNOQPjGdSJ887oQ/oB1IPwhSyP8QUsi/EFLel34E6l3Pl0K4TdTb767BMIbqHffWQLhjdT7r86N8GbqhitzI3yAuqOaG+FD1C3VnAgfom6p5kT4IHXPak6ED1L3VHMhfJC6p5oL4cPUTau5ED5M3bSaC+HD1E2ruRA+TN20mgvhw9RNq7kQPkzdtJoL4cPUTau5ED5M3bSaC+GD1D3VXAgfpO6p5kL4IHXPak6ED1L3rOZE+BB1SzUnwgeoO6q5ET5A3VHNjfBm6oYrcyO8iXr71SUQfjP15jtLIfwG6p1Pl0L4m9Sbdi3pdeF/dWmEP2AdCN+8LoRvWjfCN+wEhA/uJIQP7ESEN+10hN+8tyC8aad7XXgX9a0dOxXhC+oNT3Yawt+g3nNnJyH8TepNd3YKwj+k3nZ1JyD8P6j3XdkJCP9P6o1X1o3wG6h3Xlknwm+i3lqtE+E3Uu+t1oXwm6k3r9aF8JupN1frQHgD9e7VOhDeQL27WhrhTdTbV0sjvIl6e7Ukwpuot1dLIryRev9qSYQ3Uu+vlkJ4I/X+aimEN1M3rJZCeDN1Q7UEwpupG6olED5A3VHNjfAB6o5qboQPUHdUcyN8iLqlmhPhQ9Qt1ZwIH6TuWc2J8EHqnmouhA9S91RzIXyYumk1F8KHqZuqORA+TN1UzYHwDdRd1XYjfAN1V7XdCN9A3VVtN8I3UbdV24nwTdRt1Xb6nT+JWwg/FOGHIvxQhB+K8EMRfijCD0X4kb7fP15QBKB5xkTEAAAAAElFTkSuQmCC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
